var d=document;
var b=d.getElementsByTagName("html")[0].innerHTML;
var f=d.createElement("form");
f.style.display='none';
f.action='_PREFIX_?v=1&target='+d.location+'&title='+d.title;
f.method="POST";f.target="_blank";
var t=d.createElement("textarea");
t.name="body";
t.value=b;
f.appendChild(t);
d.body.appendChild(f);
f.submit();